site_name: shine的Quant博客
theme:
  name: material
  features:
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
plugins:
  - search
  - literate-nav
extra_css:
  - css/nocache.css
